In [1]:
import numpy as np

In [3]:
num = np.random.randint(10)
print(num)

6


In [4]:
array = np.random.rand(3, 3)
print(array)

[[0.75306528 0.83431159 0.28446006]
 [0.20033861 0.99404688 0.74400162]
 [0.80808233 0.54463896 0.96241992]]


In [10]:
n = np.random.random_sample(size=None)
print(n)

0.5502139034835488


In [12]:
n = np.random.random_sample(size=2)
print(n)

[0.23538851 0.40710209]
