In [1]:
print('Hello World')

Hello World


In [4]:
import numpy as np

In [5]:
my_list = np.array([1, 2, 3, 4, 5, 6], dtype='int8')
print(my_list)

[1 2 3 4 5 6]


In [10]:
twod_array = np.array([[1, 2, 3], [10, 20, 30]])
print(twod_array)

[[ 1  2  3]
 [10 20 30]]


In [18]:
type(np.array(twod_array))

numpy.ndarray

In [19]:
print('tralala')

tralala


In [20]:
twod_array.ndim

2

In [21]:
twod_array.shape

(2, 3)

In [22]:
my_list.size

6

In [24]:
seq = my_list

In [36]:
seq[0:5:2]

array([1, 3, 5], dtype=int8)

In [37]:
seq2 = twod_array

In [62]:
seq2[0:2]

array([[ 1,  2,  3],
       [10, 20, 30]])

In [67]:
seq2[1, 0:2]

array([10, 20])

In [69]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
np.random.randn(5)

array([ 0.63427854,  0.40095316, -1.08376989,  1.3194083 , -1.54148364])

In [77]:
reshaped_array = twod_array.reshape((1, 6))

In [78]:
print(reshaped_array)

[[ 1  2  3 10 20 30]]


In [79]:
arr1 = np.array(reshaped_array)

In [80]:
print(arr1)

[[ 1  2  3 10 20 30]]


In [81]:
arr1 is reshaped_array

False

In [82]:
arr2 = np.asarray(reshaped_array)

In [83]:
arr1 is arr2

False